### ISSUE TITLE
Aplikasi Crash

### ISSUE THREAD

**Issue by ridwanmt** [luthfiarifin/LaamMuslimAndroid#2]
Pada saat menjalankan Aplikasi, diminta permission untuk akses lokasi,, ketika di OK kan aplikasi langsung CRASH menutup sendiri ketika halaman Home.
Error: 
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
        at com.laam.laammuslim.ui.main.home.HomeViewModel.getTimePray(HomeViewModel.kt:55)

**Comment by luthfiarifin** [comment]
Oke, terimakasih. Untuk itu dikarenakan GPS yang tidak dinyalakan. Jadi saya sudah manambahkan validasi untuk GPS dan sudah membenarkan masalah error terus walaupun sudah dinyalakan dan sudah di close. Tetapi masih error apabila menyalakan GPS divalidasi dan cara untuk mengatasinya restart aplikasinya. Terimakasih. Saya close ya mas
